/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Facturacion;

import inventarios.Inventario;
import inventarios.modeloInventarios;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Angela
 */
public class facturarVentas extends javax.swing.JDialog {

    /**
     * Creates new form facturarVentas
     */
    public facturarVentas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Todos los métodos que llamamos dentro del constructor deben ir despues de initcomponets()
        confitabla();
        cargarFecha();
        this.setLocationRelativeTo(null);
    }

    //Configuración genérica para crear los encabezados de la tabla
    DefaultTableModel Mtabla;

    public void confitabla() {
        Mtabla = new DefaultTableModel() {

            //Reescribir el método para decirle que columnas son editables y cuales no
            public boolean isCellEditable(int rowIndex, int ColumnIndex) {
                //return false;
                if (ColumnIndex == 2) {
                    return true;
                } else {
                    return false;
                }
            }
        };
        Mtabla.addColumn("id");
        Mtabla.addColumn("Nombre del producto");
        Mtabla.addColumn("Cantidad");
        Mtabla.addColumn("Valor");
        Mtabla.addColumn("Total");
        jTablaFacturar.setModel(Mtabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaFacturar = new javax.swing.JTable();
        btnFacturar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnBuscarProd = new javax.swing.JButton();
        txtCod = new javax.swing.JTextField();
        txtTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro De Ventas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 71, -1, -1));

        lblFecha.setText("jTextField1");
        jPanel1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 67, 193, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Buscar Producto");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 140, -1, -1));

        jTablaFacturar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablaFacturar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTablaFacturarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTablaFacturarKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTablaFacturar);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 850, 297));

        btnFacturar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnFacturar.setText("Facturar");
        btnFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturarActionPerformed(evt);
            }
        });
        jPanel1.add(btnFacturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 316, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lista De Productos");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        btnBuscarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btnBuscarProd.setBorder(null);
        btnBuscarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 128, 58, 46));

        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });
        txtCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodKeyTyped(evt);
            }
        });
        jPanel1.add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 280, 40));

        txtTotal.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(0, 153, 0));
        txtTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTotal.setText("$0");
        txtTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 86, 320, 119));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnBuscarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdActionPerformed
        InventarioBuscar dialog = new InventarioBuscar(new javax.swing.JFrame(), true, txtCod);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnBuscarProdActionPerformed

    private void txtCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodKeyPressed
        //Buscar producto con letra b
        if (evt.getKeyCode() == KeyEvent.VK_B) {
            InventarioBuscar dialog = new InventarioBuscar(new javax.swing.JFrame(), true, txtCod);
            dialog.setVisible(true);
            if (!txtCod.getText().equals("")) {                
                llenarTablaCarrito();
            }
        }

        //Ingresar el código manualmente
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (txtCod.getText().equals("")) {

                System.out.println("Campo vacío");
                //JOptionPane.showMessageDialog(null, "aaaaaa");              

            } else {
                llenarTablaCarrito();
                System.out.println("Campo lleno");
            }
        }
    }//GEN-LAST:event_txtCodKeyPressed

    private void btnFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturarActionPerformed
        pago dialog = new pago(new javax.swing.JFrame(), true, total, this);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnFacturarActionPerformed

    //Este método es para realizar el cálculo total - la multiplicación de la cantidad con el valor en cada fila de la tabla
  
    private void jTablaFacturarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablaFacturarKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int filaeditar = jTablaFacturar.getSelectedRow();
            int numfila = jTablaFacturar.getSelectedColumnCount();
           
           
            if (filaeditar >= 0 && numfila == 1) {
                int cant = Integer.parseInt(jTablaFacturar.getValueAt(filaeditar, 2).toString());
                int valor = Integer.parseInt(jTablaFacturar.getValueAt(filaeditar, 3).toString().replaceAll(patron, ""));
              int total= cant * valor;
                jTablaFacturar.setValueAt("$" + precio_forato.format(Integer.parseInt(String.valueOf(total))), filaeditar, 4);
                sumaTotal();
            }
        }

        //Borrar producto de la tabla
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {

            if (Mtabla.getRowCount() > 0) {

                if (jTablaFacturar.getSelectedRow() != -1) {
                    int filaEliminar = jTablaFacturar.getSelectedRow();
                    Mtabla.removeRow(filaEliminar);
                    sumaTotal();
                }

            } else {
                JOptionPane.showMessageDialog(null, "No ha seleccionado ningun producto");
            }
        }
    }//GEN-LAST:event_jTablaFacturarKeyPressed

    private void jTablaFacturarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablaFacturarKeyReleased

    }//GEN-LAST:event_jTablaFacturarKeyReleased

    private void txtCodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodKeyTyped

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(facturarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(facturarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(facturarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(facturarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                facturarVentas dialog = new facturarVentas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProd;
    private javax.swing.JButton btnFacturar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaFacturar;
    private javax.swing.JTextField lblFecha;
    public javax.swing.JTextField txtCod;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables

    //
    private void llenarTablaCarrito() {
        String dato = txtCod.getText();

        controladorFacturacion control = new controladorFacturacion();
        ArrayList<modeloInventarios> rpta1 = control.listarCarrito(dato);
        ejecutarLLenarTablaCarrito(rpta1);
    }

    //metodo para recorrer los productos agregados al carrito
    public void productos() {
        DateTimeFormatter fecha = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        ArrayList<modeloDetalle> productos = new ArrayList<>();

        //No recuerdo para que es esto-----------
        modeloFacturar modelof = new modeloFacturar();
        modelof.setFecha(fecha.format(LocalDateTime.now()));
        modelof.setIdUsuario("12");
        modelof.setNeto(txtTotal.getText().replaceAll(patron, ""));
        modelof.setImpuesto("0");
        modelof.setTotal(txtTotal.getText().replaceAll(patron, ""));
        modelof.setEstado("4");

        //Recorrernviar la tabla para identificar todo lo que este allí y añadirlo al modelo
        for (int i = 0; i < jTablaFacturar.getRowCount(); i++) {
            modeloDetalle modelo = new modeloDetalle();
            modelo.setIdProducto(jTablaFacturar.getValueAt(i, 0).toString());
            modelo.setCantidad(jTablaFacturar.getValueAt(i, 2).toString());
            modelo.setValor(jTablaFacturar.getValueAt(i, 3).toString().replaceAll(patron, ""));
            modelo.setTotal(jTablaFacturar.getValueAt(i, 4).toString().replaceAll(patron, ""));
            productos.add(modelo);

        }
        controladorFacturacion control = new controladorFacturacion();
        
        
        boolean rpta = control.facturar(modelof, productos);

        if (rpta) {
            this.dispose();
            facturarVentas dialog = new facturarVentas(new javax.swing.JFrame(), true);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Error en guardar los productos");
        }
    }

    //Este método suma la cantidad total de la compra en el label txtTotal
    DecimalFormat precio_forato = new DecimalFormat("###,###"); //Este es para dar formato con punto de mil a los valores 
    String patron = "[^az AZ 0-9]"; //Quita caracteres especiales excepto los que estan allí especificados
    
    int total;

    public void sumaTotal() {
        this.total = 0;
        for (int i = 0; i < jTablaFacturar.getRowCount(); i++) {
            //getValueAt(i, 3) es el metodo que se usa para capturar la informacion de la tabla
            // el cual recibe 2 datos 
            //i = es el número de la fila, es el iterable
            //3 = es el número de la columna que necesitamos para operar, en esta caso es el valor
            //System.out.println("------- "+jTablaFacturar.getValueAt(i, 4).toString().replaceAll(patron, ""));
            int valor = Integer.parseInt(jTablaFacturar.getValueAt(i, 4).toString().replaceAll(patron, ""));
            this.total += valor;
        }
        txtTotal.setText("$" + precio_forato.format(total));
    }

    //
    private void ejecutarLLenarTablaCarrito(ArrayList<modeloInventarios> rpta1) {

        Object[] obj = new Object[5];
        for (modeloInventarios p : rpta1) {
            obj[0] = p.getId();
            obj[1] = p.getDescripcion();
            obj[2] = "1";
            if (p.getValor().equalsIgnoreCase("")) {
                obj[3] = "$0";
            } else {
                obj[3] = "$" + precio_forato.format(Integer.parseInt(p.getValor()));
            }
            obj[4] = "$" + precio_forato.format(1 * Integer.parseInt(p.getValor()));
            Mtabla.addRow(obj);
        }
        confi_tabla();

        //Cada que cargue la tabla, se borra el campo de texto, para esto es esa línea de código
        txtCod.setText("");
        sumaTotal();
    }

    private void confi_tabla() {
        TableColumnModel confi = jTablaFacturar.getColumnModel();
        jTablaFacturar.getTableHeader().setFont(new Font("Century Gothic", 1, 13));
        jTablaFacturar.setFont(new Font("Century Gothic", 0, 20));
        jTablaFacturar.setForeground(Color.WHITE);
        jTablaFacturar.setBackground(Color.GRAY);
        confi.getColumn(0).setPreferredWidth(5);
        confi.getColumn(1).setPreferredWidth(300);
        confi.getColumn(2).setPreferredWidth(5);
        confi.getColumn(3).setPreferredWidth(5);
        jTablaFacturar.setRowHeight(25);
    }

    private void cargarFecha() {

        DateTimeFormatter fecha = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        lblFecha.setText(fecha.format(LocalDateTime.now()));

    }
}
