/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Facturacion;

import java.awt.Color;
import java.awt.Font;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Alexander
 */
public class FacturaDetalle extends javax.swing.JDialog {

    /**
     * Creates new form FacturaDetalle
     */
    public FacturaDetalle(java.awt.Frame parent, boolean modal,String id,String usu,String fecha,String ttal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
        NumFac.setText(id);
        usuDetalle.setText(usu);
        fechaDetalle.setText(fecha);
        ttalFac.setText(ttal);     
        
        consultarDetalle(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        numFact = new javax.swing.JLabel();
        Usu = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        ttal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDetalle = new javax.swing.JTable();
        NumFac = new javax.swing.JLabel();
        usuDetalle = new javax.swing.JLabel();
        fechaDetalle = new javax.swing.JLabel();
        ttalFac = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numFact.setForeground(new java.awt.Color(255, 255, 255));
        numFact.setText("numFact");
        jPanel1.add(numFact, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 53, -1, -1));

        Usu.setForeground(new java.awt.Color(255, 255, 255));
        Usu.setText("Usu");
        jPanel1.add(Usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 53, -1, -1));

        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setText("Fecha");
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 53, -1, -1));

        ttal.setForeground(new java.awt.Color(255, 255, 255));
        ttal.setText("Ttal");
        jPanel1.add(ttal, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, 100, 20));

        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaDetalle);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 171, 748, 272));

        NumFac.setForeground(new java.awt.Color(255, 255, 255));
        NumFac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(NumFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 90, 20));

        usuDetalle.setForeground(new java.awt.Color(255, 255, 255));
        usuDetalle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(usuDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 130, 30));

        fechaDetalle.setForeground(new java.awt.Color(255, 255, 255));
        fechaDetalle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(fechaDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 150, 30));

        ttalFac.setForeground(new java.awt.Color(255, 255, 255));
        ttalFac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(ttalFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -2, 930, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturaDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturaDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturaDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturaDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FacturaDetalle dialog = new FacturaDetalle(new javax.swing.JFrame(), true,"","","","");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NumFac;
    private javax.swing.JLabel Usu;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel fechaDetalle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numFact;
    private javax.swing.JTable tablaDetalle;
    private javax.swing.JLabel ttal;
    private javax.swing.JLabel ttalFac;
    private javax.swing.JLabel usuDetalle;
    // End of variables declaration//GEN-END:variables

    
    private void consultarDetalle(String id) {
        controladorFacturacion control=new controladorFacturacion();
        ArrayList<modeloDetalle> rpta1=control.buscarDetalle(id);
        ejecutarLLenarTabla(rpta1);
    }
    
    
    private void confitabla() {
        TableColumnModel confi = tablaDetalle.getColumnModel();
        tablaDetalle.getTableHeader().setFont(new Font("Century Gothic", 1, 13));
        tablaDetalle.setFont(new Font("Century Gothic", 0, 20));
        tablaDetalle.setForeground(Color.WHITE);
        tablaDetalle.setBackground(Color.GRAY);
        confi.getColumn(0).setPreferredWidth(5);
        confi.getColumn(1).setPreferredWidth(200);
        confi.getColumn(2).setPreferredWidth(5);
        confi.getColumn(3).setPreferredWidth(5);
        confi.getColumn(4).setPreferredWidth(5);
        tablaDetalle.setRowHeight(25);
    }
    
    
    DecimalFormat precio_forato = new DecimalFormat("###,###");
    
    private void ejecutarLLenarTabla(ArrayList<modeloDetalle> rpta1) {
        DefaultTableModel Mtabla = new DefaultTableModel();
        
        Mtabla=new DefaultTableModel(){
        };
        Mtabla.addColumn("Id");
        Mtabla.addColumn("Producto");
        Mtabla.addColumn("Valor");
        Mtabla.addColumn("Cantidad");
        Mtabla.addColumn("Total");
        tablaDetalle.setModel(Mtabla);
        
        Object[] obj = new Object[5];
        for (modeloDetalle p : rpta1) {
            obj[0] = p.getId();
            obj[1] = p.getIdProducto();
            
            if (p.getValor().equalsIgnoreCase("")) {
                obj[2] = "$0";
            } else {
                obj[2] = "$" + precio_forato.format(Integer.parseInt(p.getValor()));
            }
            
            obj[3] = p.getCantidad();
            
            if (p.getTotal().equalsIgnoreCase("")) {
                obj[4] = "$0";
            } else {
                obj[4] = "$" + precio_forato.format(Integer.parseInt(p.getTotal()));
            }
            Mtabla.addRow(obj);
        }
        confitabla();
    }
}
