/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Facturacion;


import ds.desktop.notify.DesktopNotify;
import inventarios.controladorInventarios;
import inventarios.modeloInventarios;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Angela
 */
public class InventarioBuscar extends javax.swing.JDialog {

    /**
     * Creates new form I
     */
    
    //Variable global que recibe lo que trae el campo txtCod de la interfaz facturarVentas
    JTextField txtCod;
    
    
    //JTextField txtCod - Siempre que lo llame desde otra interfaz debo agregarlo en el constructor
    public InventarioBuscar(java.awt.Frame parent, boolean modal,JTextField txtCod) { 
        super(parent, modal);
        initComponents(); //Colocar todo despues de este initComponents
        setLocationRelativeTo(null);
        this.txtCod=txtCod;
        llenarTabla();
        //DesktopNotify.showDesktopMessage("Notificacion", "\nPara editar dar doble clik en el producto deseado", DesktopNotify.SUCCESS, 20000); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloProductoInv = new javax.swing.JLabel();
        tituloInventario = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnCerrarUsu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloProductoInv.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tituloProductoInv.setForeground(new java.awt.Color(204, 204, 204));
        tituloProductoInv.setText("Nombre Producto");
        jPanel1.add(tituloProductoInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 160, -1));

        tituloInventario.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        tituloInventario.setForeground(new java.awt.Color(204, 204, 204));
        tituloInventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloInventario.setText("Inventario");
        jPanel1.add(tituloInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 410, 40));

        btnCerrarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        btnCerrarUsu.setBorder(null);
        btnCerrarUsu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarUsuActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 10, -1, -1));

        txtTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        txtTabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTablaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtTabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 1330, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1375, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarUsuActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarUsuActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        buscar();
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtTablaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTablaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
           pasar();
        }
    }//GEN-LAST:event_txtTablaKeyPressed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventarioBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventarioBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventarioBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventarioBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InventarioBuscar dialog = new InventarioBuscar(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarUsu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tituloInventario;
    private javax.swing.JLabel tituloProductoInv;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTable txtTabla;
    // End of variables declaration//GEN-END:variables

    
    //Este método es una configuración general de tipografía, tamaño de texto y tamaño de largo de cada casilla de la tabla
    public void confi_tabla() {
        TableColumnModel confi = txtTabla.getColumnModel();
        txtTabla.getTableHeader().setFont(new Font("Century Gothic", 1, 13));
        txtTabla.setFont(new Font("Century Gothic", 0, 20));
        txtTabla.setForeground(Color.WHITE);
        txtTabla.setBackground(Color.GRAY);
        confi.getColumn(0).setPreferredWidth(5);
        confi.getColumn(1).setPreferredWidth(600);
        confi.getColumn(2).setPreferredWidth(5);
        confi.getColumn(3).setPreferredWidth(5);
        confi.getColumn(4).setPreferredWidth(5);
        confi.getColumn(5).setPreferredWidth(5);
        txtTabla.setRowHeight(25);
    }
    
    
    //Este método llena la tabla que consulta los productos
    private void llenarTabla() {
        controladorInventarios control = new controladorInventarios();
        ArrayList<modeloInventarios> rpta1 = control.listar();
        ejecutarLLenarTabla(rpta1);
    }

    
    //Este método busca un producto especifico cuando va al controlador y se filtra de acuerdo al caracter que se ingrese
    private void buscar() {
        String dato = txtBuscar.getText();
        System.out.println("-------------> " + dato);
        controladorInventarios control = new controladorInventarios();
        ArrayList<modeloInventarios> rpta3 = control.buscar(dato);
        ejecutarLLenarTabla(rpta3);
    }

    
    //Este método crea los encabezados de la tabla y da formato a los valores numéricos.
    DecimalFormat precio_forato = new DecimalFormat("###,###");
    private void ejecutarLLenarTabla(ArrayList<modeloInventarios> rpta1) {
        DefaultTableModel Mtabla = new DefaultTableModel();
        Mtabla= new DefaultTableModel() {

            //Reescribir el método para decirle que columnas son editables y cuales no
            public boolean isCellEditable(int rowIndex, int ColumnIndex) {
                //return false;
                 return false;
            }
        };
        Mtabla.addColumn("Id");
        Mtabla.addColumn("Descripción");
        Mtabla.addColumn("Valor");
        Mtabla.addColumn("Costo");
        Mtabla.addColumn("Cantidad");
        Mtabla.addColumn("Estado");
        txtTabla.setModel(Mtabla);
        Object[] obj = new Object[6];
        for (modeloInventarios p : rpta1) {
            obj[0] = p.getId();
            obj[1] = p.getDescripcion();
            if (p.getValor().equalsIgnoreCase("")) {
                obj[2] = "$0";
            } else {
                obj[2] = "$" + precio_forato.format(Integer.parseInt(p.getValor()));
            }
            if (p.getCosto().equalsIgnoreCase("")) {
                obj[3] = "$0";
            } else {
                obj[3] = "$" + precio_forato.format(Integer.parseInt(p.getCosto()));
            }
            obj[4] = p.getCantidad();
            obj[5] = p.getEstado();
            Mtabla.addRow(obj);
        }
        confi_tabla();
    }

    
    public void pasar(){
            
        int filaeditar = txtTabla.getSelectedRow();
        int numfila = txtTabla.getSelectedColumnCount();

        if (filaeditar >= 0 && numfila == 1) {
            
            //Capturando la información de la tabla y pasandola al JTXTFIELD en dos líneas de código
            //String cod=txtTabla.getValueAt(filaeditar, 0).toString();
            //txtCod.setText(cod);
    
            //Exactamente lo mismo de arriba pero en una sola línea
            txtCod.setText(txtTabla.getValueAt(filaeditar, 0).toString());
            this.dispose();
        }
    }
}
