/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Facturacion;

import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Angela
 */
public class pago extends javax.swing.JDialog {

    /**
     * Creates new form pago
     */
    
    int Total;
    facturarVentas factura;
            
    public pago(java.awt.Frame parent, boolean modal, int Total,facturarVentas factura) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.Total=Total; 
        this.factura=factura;
        mostrarTotal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTituloTotal = new javax.swing.JLabel();
        lbTituloEfectivo = new javax.swing.JLabel();
        lbTituloCambio = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        txtEfectivo = new javax.swing.JTextField();
        lbCambio = new javax.swing.JLabel();
        btnPagar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTituloTotal.setForeground(new java.awt.Color(255, 255, 255));
        lbTituloTotal.setText("Total");
        jPanel1.add(lbTituloTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        lbTituloEfectivo.setForeground(new java.awt.Color(255, 255, 255));
        lbTituloEfectivo.setText("Efectivo");
        jPanel1.add(lbTituloEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        lbTituloCambio.setForeground(new java.awt.Color(255, 255, 255));
        lbTituloCambio.setText("Cambio");
        jPanel1.add(lbTituloCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        lbTotal.setForeground(new java.awt.Color(255, 255, 255));
        lbTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(lbTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 140, 30));

        txtEfectivo.setBackground(new java.awt.Color(0, 0, 0));
        txtEfectivo.setForeground(new java.awt.Color(255, 255, 255));
        txtEfectivo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtEfectivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEfectivoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEfectivoKeyTyped(evt);
            }
        });
        jPanel1.add(txtEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 140, 27));

        lbCambio.setForeground(new java.awt.Color(255, 255, 255));
        lbCambio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCambio.setText("$ 00.000");
        lbCambio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(lbCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 190, 30));

        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        jPanel1.add(btnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 170, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        btnCerrar.setBorder(null);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    
    DecimalFormat precio_forato = new DecimalFormat("###,###"); //Este es para dar formato con punto de mil a los valores
    String patron="[^az AZ 0-9]"; //Quita caracteres especiales excepto los que estan allí especificados
 
    private void txtEfectivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEfectivoKeyReleased
        int total = Integer.parseInt(lbTotal.getText().replaceAll(patron, "")) ;
        int efectivo = Integer.parseInt(txtEfectivo.getText().replaceAll(patron, ""));
        
        txtEfectivo.setText("$"+precio_forato.format(efectivo));
        
        
        int gTotal= efectivo-total;
        
        lbCambio.setText("$"+precio_forato.format(gTotal));
        
        if (total > efectivo) {
            lbCambio.setForeground(Color.red);
        } else {
            lbCambio.setForeground(Color.green);
        }
    }//GEN-LAST:event_txtEfectivoKeyReleased

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        
        JOptionPane.showMessageDialog(null,"Compra Exitosa");
        factura.productos();
        this.dispose();
    }//GEN-LAST:event_btnPagarActionPerformed

    private void txtEfectivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEfectivoKeyTyped
       char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtEfectivoKeyTyped

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                pago dialog = new pago(new javax.swing.JFrame(), true, 0,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCambio;
    private javax.swing.JLabel lbTituloCambio;
    private javax.swing.JLabel lbTituloEfectivo;
    private javax.swing.JLabel lbTituloTotal;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JTextField txtEfectivo;
    // End of variables declaration//GEN-END:variables

    private void mostrarTotal() {
        lbTotal.setText("$"+ precio_forato.format(Total));
    }
}
