/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compras;

import inventarios.*;
import Facturacion.InventarioBuscar;
import Facturacion.controladorFacturacion;
import ds.desktop.notify.DesktopNotify;
import java.applet.AudioClip;
import java.awt.event.KeyEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;



public class RegistrarCompra extends javax.swing.JDialog {

    /**
     * Creates new form Registrar
     */
    public RegistrarCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        cargarFecha();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloInventario = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAgregarInventario = new javax.swing.JButton();
        txtcantidad = new javax.swing.JTextField();
        txtCod = new javax.swing.JTextField();
        tituloInventario1 = new javax.swing.JLabel();
        btnCerrarUsu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBuscarPro = new javax.swing.JButton();
        txtNomPro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fechaCompra = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        tituloInventario.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        tituloInventario.setForeground(new java.awt.Color(204, 204, 204));
        tituloInventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloInventario.setText("Inventario");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar.png"))); // NOI18N
        btnAgregarInventario.setBorder(null);
        btnAgregarInventario.setBorderPainted(false);
        btnAgregarInventario.setContentAreaFilled(false);
        btnAgregarInventario.setDefaultCapable(false);
        btnAgregarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarInventarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 210, 50));

        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcantidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidadKeyTyped(evt);
            }
        });
        jPanel1.add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 100, 40));

        txtCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodKeyTyped(evt);
            }
        });
        jPanel1.add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 100, 40));

        tituloInventario1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        tituloInventario1.setForeground(new java.awt.Color(255, 255, 255));
        tituloInventario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloInventario1.setText("Registrar Compras");
        jPanel1.add(tituloInventario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        btnCerrarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        btnCerrarUsu.setBorder(null);
        btnCerrarUsu.setBorderPainted(false);
        btnCerrarUsu.setContentAreaFilled(false);
        btnCerrarUsu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarUsuActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Cantidad");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 70, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Código Producto");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 110, -1));

        btnBuscarPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btnBuscarPro.setBorder(null);
        btnBuscarPro.setBorderPainted(false);
        btnBuscarPro.setContentAreaFilled(false);
        btnBuscarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 50, 50));

        txtNomPro.setEditable(false);
        jPanel1.add(txtNomPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 280, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Nombre Producto");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 110, -1));

        fechaCompra.setForeground(new java.awt.Color(255, 255, 255));
        fechaCompra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(fechaCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 90, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 40, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarInventarioActionPerformed
        guardarCompra();
    }//GEN-LAST:event_btnAgregarInventarioActionPerformed

    private void btnCerrarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarUsuActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarUsuActionPerformed

    private void txtcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyTyped
       char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtcantidadKeyTyped

    private void btnBuscarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProActionPerformed
        InventarioBuscar dialog = new InventarioBuscar(new javax.swing.JFrame(), true, txtCod);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnBuscarProActionPerformed

    private void txtCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodKeyPressed
        //Buscar producto con letra b
        if (evt.getKeyCode() == KeyEvent.VK_B) {
            InventarioBuscar dialog = new InventarioBuscar(new javax.swing.JFrame(), true, txtCod);
            dialog.setVisible(true);
            if (!txtCod.getText().equals("")) {                
                llenarLabel();
                
                //Posterior a elegir a el producto el cursor se para en este campo
                txtcantidad.requestFocus();
            }
        }

        //Ingresar el código manualmente
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (txtCod.getText().equals("")) {

                System.out.println("Campo vacío");
                JOptionPane.showMessageDialog(null, "Selecciona un producto");              

            } else {
                llenarLabel();
                
                //Posterior a elegir a el código el cursor se va para la casilla de texto cantidad
                txtcantidad.requestFocus();
                System.out.println("Campo lleno");
            }
        }
    }//GEN-LAST:event_txtCodKeyPressed

    private void txtCodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodKeyTyped

    private void txtcantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            guardarCompra();
            
            //Posterior a elegir la cantidad el cursor se va para la casilla de texto código
            txtCod.requestFocus();
        }
    }//GEN-LAST:event_txtcantidadKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistrarCompra dialog = new RegistrarCompra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarInventario;
    private javax.swing.JButton btnBuscarPro;
    private javax.swing.JButton btnCerrarUsu;
    private javax.swing.JLabel fechaCompra;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tituloInventario;
    private javax.swing.JLabel tituloInventario1;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtNomPro;
    private javax.swing.JTextField txtcantidad;
    // End of variables declaration//GEN-END:variables


      //-------------------------------------------------------------------------------------------------------------------------------------
      //CONSULTAR EL NOMBRE DEL PRODUCTO A TRAVÉS DEL CÓDIGO
    private void llenarLabel() {
        String cod = txtCod.getText();
        
        controladorCompras control=new controladorCompras();
        modeloInventarios modelo = control.buscarCod(cod);
        
        if (modelo.getId().equals(" ")){
            System.out.println("Es nullo");
        } else {
            txtNomPro.setText(modelo.getDescripcion());
        }
    }


    private void guardarCompra() {
        //GUARDAR EL REGISTRO DE LA COMPRA EN LA TABLA COMPRAS DE LA BD
        //SUMAR AL INVENTARIO LA CANTIDAD AGREGADA
        
        String nomFecha = fechaCompra.getText();
        String cod = txtCod.getText();
        String nom = txtNomPro.getText();
        String cant = txtcantidad.getText();
        
        modeloCompras modelo = new modeloCompras();
        modelo.setId(cod);
        modelo.setFecha(nomFecha);
        modelo.setProducto(nom);
        modelo.setCantidad(cant);
        
        controladorCompras control = new controladorCompras();
        
        if (control.guardarCompra(modelo)) {
            DesktopNotify.showDesktopMessage("Notificacion", "\n Registro Exitoso", DesktopNotify.SUCCESS, 20000);
            notificacion();
            
            //Limpiar los campos de texto
            txtCod.setText("");
            txtNomPro.setText("");
            txtcantidad.setText("");
        } else {
            DesktopNotify.showDesktopMessage("Notificacion", "\n Registro no Exitoso", DesktopNotify.ERROR, 20000);
        }  
    }

    private void cargarFecha() {
        DateTimeFormatter fecha = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        fechaCompra.setText(fecha.format(LocalDateTime.now()));
    }

    private void notificacion() {
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/notificacion/notifi.wav"));
        sonido.play();
    }
}
