/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Usuarios;

import ds.desktop.notify.DesktopNotify;
import java.applet.AudioClip;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class registrarUsuario extends javax.swing.JDialog {

    /**
     * Creates new form Usuarios
     */
    public registrarUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        llenarRoles();
        llenarTipoDocumento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        IconoUsu = new javax.swing.JLabel();
        tituloUsu = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbTipoDocumentoUsu = new javax.swing.JLabel();
        lbDocumentoUsu = new javax.swing.JLabel();
        lbTelefonoUsu = new javax.swing.JLabel();
        lbDireccionUsu = new javax.swing.JLabel();
        lbRolUsu = new javax.swing.JLabel();
        lbUsu = new javax.swing.JLabel();
        lbPass = new javax.swing.JLabel();
        txtNombreUsu = new javax.swing.JTextField();
        cBoxTipoDocUsu = new javax.swing.JComboBox<>();
        txtDocumentoUsu = new javax.swing.JTextField();
        txtTelefonoUsu = new javax.swing.JTextField();
        txtDireccionUsu = new javax.swing.JTextField();
        cBoxRolUsu = new javax.swing.JComboBox<>();
        txtUsu = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btn_registrarUsuario = new javax.swing.JButton();
        btnModificarUsu = new javax.swing.JButton();
        btn_cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        IconoUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grupo.png"))); // NOI18N
        jPanel1.add(IconoUsu);
        IconoUsu.setBounds(110, 10, 130, 140);

        tituloUsu.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        tituloUsu.setForeground(new java.awt.Color(255, 255, 255));
        tituloUsu.setText("REGISTRAR USUARIOS");
        jPanel1.add(tituloUsu);
        tituloUsu.setBounds(100, 140, 160, 40);

        lbNombre.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(255, 255, 255));
        lbNombre.setText("Nombre ");
        jPanel1.add(lbNombre);
        lbNombre.setBounds(20, 210, 70, 17);

        lbTipoDocumentoUsu.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lbTipoDocumentoUsu.setForeground(new java.awt.Color(255, 255, 255));
        lbTipoDocumentoUsu.setText("Tipo Documento");
        jPanel1.add(lbTipoDocumentoUsu);
        lbTipoDocumentoUsu.setBounds(20, 250, 130, 20);

        lbDocumentoUsu.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lbDocumentoUsu.setForeground(new java.awt.Color(255, 255, 255));
        lbDocumentoUsu.setText("Documento");
        jPanel1.add(lbDocumentoUsu);
        lbDocumentoUsu.setBounds(20, 290, 90, 17);

        lbTelefonoUsu.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lbTelefonoUsu.setForeground(new java.awt.Color(255, 255, 255));
        lbTelefonoUsu.setText("Teléfono");
        jPanel1.add(lbTelefonoUsu);
        lbTelefonoUsu.setBounds(20, 330, 70, 17);

        lbDireccionUsu.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lbDireccionUsu.setForeground(new java.awt.Color(255, 255, 255));
        lbDireccionUsu.setText("Dirección");
        jPanel1.add(lbDireccionUsu);
        lbDireccionUsu.setBounds(20, 370, 90, 17);

        lbRolUsu.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lbRolUsu.setForeground(new java.awt.Color(255, 255, 255));
        lbRolUsu.setText("Rol");
        jPanel1.add(lbRolUsu);
        lbRolUsu.setBounds(20, 410, 34, 14);

        lbUsu.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lbUsu.setForeground(new java.awt.Color(255, 255, 255));
        lbUsu.setText("Usuario");
        jPanel1.add(lbUsu);
        lbUsu.setBounds(20, 450, 80, 17);

        lbPass.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lbPass.setForeground(new java.awt.Color(255, 255, 255));
        lbPass.setText("Password");
        jPanel1.add(lbPass);
        lbPass.setBounds(20, 490, 80, 17);

        txtNombreUsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreUsuKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombreUsu);
        txtNombreUsu.setBounds(160, 200, 160, 30);

        cBoxTipoDocUsu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        cBoxTipoDocUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxTipoDocUsuActionPerformed(evt);
            }
        });
        jPanel1.add(cBoxTipoDocUsu);
        cBoxTipoDocUsu.setBounds(160, 240, 160, 20);

        txtDocumentoUsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDocumentoUsuKeyTyped(evt);
            }
        });
        jPanel1.add(txtDocumentoUsu);
        txtDocumentoUsu.setBounds(160, 280, 160, 30);

        txtTelefonoUsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoUsuKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelefonoUsu);
        txtTelefonoUsu.setBounds(160, 320, 160, 30);
        jPanel1.add(txtDireccionUsu);
        txtDireccionUsu.setBounds(160, 360, 160, 30);

        cBoxRolUsu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        cBoxRolUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxRolUsuActionPerformed(evt);
            }
        });
        jPanel1.add(cBoxRolUsu);
        cBoxRolUsu.setBounds(160, 400, 160, 30);
        jPanel1.add(txtUsu);
        txtUsu.setBounds(160, 440, 160, 30);
        jPanel1.add(txtPass);
        txtPass.setBounds(160, 480, 160, 30);

        btn_registrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar.png"))); // NOI18N
        btn_registrarUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        btn_registrarUsuario.setContentAreaFilled(false);
        btn_registrarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_registrarUsuario.setFocusPainted(false);
        btn_registrarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registrarUsuarioMouseClicked(evt);
            }
        });
        btn_registrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btn_registrarUsuario);
        btn_registrarUsuario.setBounds(30, 540, 190, 50);

        btnModificarUsu.setBackground(new java.awt.Color(51, 51, 51));
        btnModificarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        btnModificarUsu.setBorder(null);
        btnModificarUsu.setBorderPainted(false);
        btnModificarUsu.setContentAreaFilled(false);
        btnModificarUsu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarUsuActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarUsu);
        btnModificarUsu.setBounds(240, 540, 60, 50);

        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        btn_cerrar.setBorder(null);
        btn_cerrar.setBorderPainted(false);
        btn_cerrar.setContentAreaFilled(false);
        btn_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cerrar.setDefaultCapable(false);
        btn_cerrar.setFocusPainted(false);
        btn_cerrar.setFocusable(false);
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cerrar);
        btn_cerrar.setBounds(310, 10, 30, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btnModificarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarUsuActionPerformed
        VistaUsuario dialog = new VistaUsuario(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnModificarUsuActionPerformed

    private void btn_registrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarUsuarioActionPerformed
        guardarUsu();
    }//GEN-LAST:event_btn_registrarUsuarioActionPerformed

    private void btn_registrarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarUsuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_registrarUsuarioMouseClicked

    private void txtDocumentoUsuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocumentoUsuKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtDocumentoUsuKeyTyped

    private void txtTelefonoUsuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoUsuKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoUsuKeyTyped

    private void txtNombreUsuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreUsuKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;
        boolean espacio = key == 32;

        if (!(minusculas || mayusculas || espacio)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreUsuKeyTyped

    private void cBoxRolUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxRolUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBoxRolUsuActionPerformed

    private void cBoxTipoDocUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxTipoDocUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBoxTipoDocUsuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                registrarUsuario dialog = new registrarUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconoUsu;
    private javax.swing.JButton btnModificarUsu;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_registrarUsuario;
    private javax.swing.JComboBox<String> cBoxRolUsu;
    private javax.swing.JComboBox<String> cBoxTipoDocUsu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbDireccionUsu;
    private javax.swing.JLabel lbDocumentoUsu;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbPass;
    private javax.swing.JLabel lbRolUsu;
    private javax.swing.JLabel lbTelefonoUsu;
    private javax.swing.JLabel lbTipoDocumentoUsu;
    private javax.swing.JLabel lbUsu;
    private javax.swing.JLabel tituloUsu;
    private javax.swing.JTextField txtDireccionUsu;
    private javax.swing.JTextField txtDocumentoUsu;
    private javax.swing.JTextField txtNombreUsu;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtTelefonoUsu;
    private javax.swing.JTextField txtUsu;
    // End of variables declaration//GEN-END:variables

    private void guardarUsu() {
        String nombreUsu = txtNombreUsu.getText();
        String tipoDocUsu = idTipoDocumento(); //SE ENVÍA EL METODO IDTIPODOCUMENTO() - Q ES EL Q CAPTURA EL ID DEL TIPO DOCUMENTO SELECCIONADO
        String documentoUsu = txtDocumentoUsu.getText();
        String telefonoUsu = txtTelefonoUsu.getText();
        String direccionUsu = txtDireccionUsu.getText();
        String rolUsu = idRol(); //SE ENVÍA EL METODO IDROL() - Q ES EL Q CAPTURA EL ID DEL ROL SELECCIONADO
        String usuUsu = txtUsu.getText();
        String passUsu = String.valueOf(txtPass.getPassword());

        modeloUsuario modelo = new modeloUsuario();
        modelo.setUsuario(nombreUsu);
        modelo.setTipoDocumento(tipoDocUsu);
        modelo.setDocumento(documentoUsu);
        modelo.setTelefono(telefonoUsu);
        modelo.setDireccion(direccionUsu);
        modelo.setRol(rolUsu);
        modelo.setUsu(usuUsu);
        modelo.setPass(getMD5(passUsu));

        controladorUsuario control = new controladorUsuario();

        //PARA DEMAS REGISTROS DEL USUARIO
        if (control.guardar(modelo)) {
            DesktopNotify.showDesktopMessage("Notificacion", "\n Registro Exitoso", DesktopNotify.SUCCESS, 20000);
            notificacion();
            borrar();
        } else {
            DesktopNotify.showDesktopMessage("Notificacion", "\n Registro no Exitoso", DesktopNotify.ERROR, 20000);
        }
    }

    //METODO BORRAR CAMPOS
    void borrar() {
        txtNombreUsu.setText("");
        cBoxTipoDocUsu.setSelectedItem("");
        txtDocumentoUsu.setText("");
        txtTelefonoUsu.setText("");
        txtDireccionUsu.setText("");
        cBoxRolUsu.setSelectedItem("");
        txtUsu.setText("");
        txtPass.setText("");
    }

    //METODO NOTIFICACIONES -AUDIO
    public void notificacion() {
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/notificacion/notifi.wav"));
        sonido.play();
    }

    //COMBO BOX ROL
    //ARRELGO GLOBAL
    ArrayList<modeloRol> rpta1 = new ArrayList<>();

    //COMBO BOX ROL - TRAE EL NOMBRE DEL ROL - MOSTRAR EN LA VISTA
    private void llenarRoles() {
        controladorUsuario control = new controladorUsuario();
        rpta1 = control.consultaRol();
        cBoxRolUsu.removeAllItems();
        cBoxRolUsu.addItem("Selecciona");

        for (int i = 0; i < rpta1.size(); i++) {
            cBoxRolUsu.addItem(rpta1.get(i).getRol());
        }
    }

    //COMBO BOX ROL - TRAE EL ID DEL ROL - ENVIAR A LA BD
    String idRol() {
        String id = "";
        String dato = cBoxRolUsu.getSelectedItem().toString();
        //String index=String.valueOf(cbRol.getSelectedIndex());
        //System.out.println(" ----  "+dato);
        for (int i = 0; i < this.rpta1.size(); i++) {
            if (rpta1.get(i).getRol().equals(dato)) {
                id = rpta1.get(i).getId();
                //System.out.println("--------> "+id);
            }
        }
        return id;
    }

    //COMBO BOX TIPO DE DOCUMENTO
    //ARRELGO GLOBAL
    ArrayList<modeloTipoDocumento> rpta2 = new ArrayList<>();

    //COMBO BOX ROL - TRAE EL NOMBRE DEL ROL - MOSTRAR EN LA VISTA
    private void llenarTipoDocumento() {

        controladorUsuario control = new controladorUsuario();
        rpta2 = control.consultaTipoDocumento();
        cBoxTipoDocUsu.removeAllItems();
        cBoxTipoDocUsu.addItem("Selecciona");

        for (int i = 0; i < rpta2.size(); i++) {
            cBoxTipoDocUsu.addItem(rpta2.get(i).getTipoDocumento());

        }
    }

    //COMBO BOX ROL - TRAE EL ID DEL ROL - ENVIAR A LA BD
    String idTipoDocumento() {
        String id = "";
        String dato = cBoxTipoDocUsu.getSelectedItem().toString();
        //String index=String.valueOf(cbRol.getSelectedIndex());
        //System.out.println(" ----  "+dato);
        for (int i = 0; i < this.rpta2.size(); i++) {
            if (rpta2.get(i).getTipoDocumento().equals(dato)) {
                id = rpta2.get(i).getId();
                //System.out.println("--------> "+id);
            }
        }
        return id;
    }
    
    
     public String getMD5(String input) {
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] messageDigest = md.digest(input.getBytes());
            BigInteger number = new BigInteger(1, messageDigest);

            String hashtext = number.toString(16);
            System.out.println(hashtext);

            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
            return hashtext;
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }
}
