/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Usuarios;

import ds.desktop.notify.DesktopNotify;
import java.awt.Color;
import java.awt.Font;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author User
 */
public class VistaUsuario extends javax.swing.JDialog {

    /**
     * Creates new form VistaUsuario
     */
    public VistaUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        llenarTabla();
        DesktopNotify.showDesktopMessage("Notificacion", "\nPara editar dar doble clik en el usuario deseado", DesktopNotify.SUCCESS, 20000); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaUsuario = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtBuscarUsu = new javax.swing.JTextField();
        btn_cerrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grupo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 0, 140, 140);

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USUARIOS");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 80, 150, 40);

        jTablaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablaUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTablaUsuarioKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTablaUsuario);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 170, 1140, 470);

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Buscar Usuario");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(520, 90, 110, 20);

        txtBuscarUsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarUsuKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscarUsu);
        txtBuscarUsu.setBounds(380, 120, 400, 30);

        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        btn_cerrar.setBorder(null);
        btn_cerrar.setBorderPainted(false);
        btn_cerrar.setContentAreaFilled(false);
        btn_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cerrar.setDefaultCapable(false);
        btn_cerrar.setFocusPainted(false);
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cerrar);
        btn_cerrar.setBounds(1140, 10, 24, 24);

        jLabel4.setText("Paa editar dar doble clik en el producto deseado");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(450, 650, 280, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1189, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void txtBuscarUsuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarUsuKeyReleased
        buscar();
    }//GEN-LAST:event_txtBuscarUsuKeyReleased

    private void jTablaUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablaUsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.out.println("-------------> evento");
            editar();
        }
    }//GEN-LAST:event_jTablaUsuarioKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaUsuario dialog = new VistaUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaUsuario;
    private javax.swing.JTextField txtBuscarUsu;
    // End of variables declaration//GEN-END:variables

    private void llenarTabla() {
        controladorUsuario control = new controladorUsuario();
        ArrayList<modeloUsuario> rpta1 = control.listar();
        ejecutarLLenarTabla(rpta1);
    }
    
    public void confi_tabla() {
        TableColumnModel confi = jTablaUsuario.getColumnModel();
        jTablaUsuario.getTableHeader().setFont(new Font("Century Gothic", 1, 13));
        jTablaUsuario.setFont(new Font("Century Gothic", 0, 20));
        jTablaUsuario.setForeground(Color.WHITE);
        jTablaUsuario.setBackground(Color.GRAY);
        confi.getColumn(0).setPreferredWidth(5);
        confi.getColumn(1).setPreferredWidth(150);
        confi.getColumn(2).setPreferredWidth(5);
        confi.getColumn(3).setPreferredWidth(5);
        confi.getColumn(4).setPreferredWidth(5);
        confi.getColumn(5).setPreferredWidth(5);
        confi.getColumn(6).setPreferredWidth(50);
        confi.getColumn(7).setPreferredWidth(5);
        jTablaUsuario.setRowHeight(25);

    }

    private void buscar() {
        String dato = txtBuscarUsu.getText();
        System.out.println("-------------> " + dato);
        controladorUsuario control = new controladorUsuario();
        ArrayList<modeloUsuario> rpta3 = control.buscar(dato);
        ejecutarLLenarTabla(rpta3);
    }
    
    private void ejecutarLLenarTabla(ArrayList<modeloUsuario> rpta1) {
        DefaultTableModel Mtabla = new DefaultTableModel();
        Mtabla.addColumn("Id");
        Mtabla.addColumn("Nombre Empleado");
        Mtabla.addColumn("Tipo Documento");
        Mtabla.addColumn("Documento");
        Mtabla.addColumn("Teléfono");
        Mtabla.addColumn("Dirección");
        Mtabla.addColumn("Rol");
        Mtabla.addColumn("Estado");
        jTablaUsuario.setModel(Mtabla);
        
        Object[] obj = new Object[8];
        for (modeloUsuario p : rpta1) {
            obj[0] = p.getId();
            obj[1] = p.getUsuario();
            obj[2] = p.getTipoDocumento();
            obj[3] = p.getDocumento();
            obj[4] = p.getTelefono();
            obj[5] = p.getDireccion();
            obj[6] = p.getRol();
            obj[7] = p.getEstado();
            
            Mtabla.addRow(obj);
        }
        confi_tabla();
    }

    private void editar() {
        modeloUsuario modelo = new modeloUsuario();
        int filaeditar = jTablaUsuario.getSelectedRow();
        int numfila = jTablaUsuario.getSelectedColumnCount();

        if (filaeditar >= 0 && numfila == 1) {
            modelo.setId(jTablaUsuario.getValueAt(filaeditar, 0).toString());
            modelo.setUsuario(jTablaUsuario.getValueAt(filaeditar, 1).toString());
            modelo.setTipoDocumento(jTablaUsuario.getValueAt(filaeditar, 2).toString());
            modelo.setDocumento(jTablaUsuario.getValueAt(filaeditar, 3).toString());
            modelo.setTelefono(jTablaUsuario.getValueAt(filaeditar, 4).toString());
            modelo.setDireccion(jTablaUsuario.getValueAt(filaeditar, 5).toString());
            modelo.setRol(jTablaUsuario.getValueAt(filaeditar, 6).toString());
            modelo.setEstado("1");
        }
        
        controladorUsuario control=new controladorUsuario();
        boolean rpta=control.editar(modelo);
        
        if (rpta) {
            DesktopNotify.showDesktopMessage("Notificacion", "\n Registro Exitoso", DesktopNotify.SUCCESS, 20000); 
            llenarTabla();
        }else{
            DesktopNotify.showDesktopMessage("Notificacion", "\n Registro no Exitoso", DesktopNotify.SUCCESS, 20000); 
        }
    }
}
